version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-packages-

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # run tests!
      - run:
          name: Lint & Typecheck
          command: yarn lint && yarn type-check

      - run:
          name: Run tests
          command: yarn test --coverage

      - run:
          context: pinjollist-codecov
          name: Upload Coverage
          command: yarn report-coverage
